
import React, { useState, useCallback, useMemo } from 'react';
import { 
  ChevronRight, 
  ChevronLeft, 
  Calendar, 
  User, 
  Clock, 
  Phone, 
  CheckCircle2, 
  MessageCircle,
  AlertCircle,
  ShieldCheck,
  Star,
  Users,
  Briefcase,
  Sparkles
} from 'lucide-react';
import { Step, FormData, Doctor } from './types';
import { DOCTORS, CLINIC_CONFIG, APPOINTMENT_TYPES } from './constants';
import { summarizeHealthReason } from './services/geminiService';

const App: React.FC = () => {
  const [currentStep, setCurrentStep] = useState<Step>(Step.Welcome);
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [aiSummary, setAiSummary] = useState<string>('');
  const [formData, setFormData] = useState<FormData>({
    patientName: '',
    phoneNumber: '',
    email: '',
    reasonForVisit: '',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '',
    doctorId: null,
    appointmentType: 'consultation'
  });

  const selectedDoctor = useMemo(() => 
    DOCTORS.find(d => d.id === formData.doctorId), 
  [formData.doctorId]);

  const handleNext = async () => {
    if (currentStep === Step.PatientInfo && !aiSummary) {
      setIsSummarizing(true);
      const summary = await summarizeHealthReason(formData.reasonForVisit);
      setAiSummary(summary);
      setIsSummarizing(false);
    }
    setCurrentStep(prev => (prev + 1) as Step);
  };

  const handleBack = () => setCurrentStep(prev => (prev - 1) as Step);

  const updateFormData = (updates: Partial<FormData>) => {
    setFormData(prev => ({ ...prev, ...updates }));
  };

  const isStepValid = useMemo(() => {
    switch (currentStep) {
      case Step.PatientInfo:
        return formData.patientName.length >= 2 && 
               formData.phoneNumber.length >= 8 && 
               formData.reasonForVisit.length >= 10;
      case Step.DoctorSelection:
        return formData.doctorId !== null;
      case Step.DateTimeSelection:
        return !!formData.appointmentDate && !!formData.appointmentTime;
      default:
        return true;
    }
  }, [currentStep, formData]);

  const generateWhatsAppURL = () => {
    const message = `*HealthPlus Concierge Booking*
    
*Patient:* ${formData.patientName}
*Phone:* ${formData.phoneNumber}
*Doctor:* ${selectedDoctor?.name}
*Specialty:* ${selectedDoctor?.specialty}
*Time:* ${formData.appointmentDate} at ${formData.appointmentTime}

*Patient Intake Summary:*
${aiSummary || formData.reasonForVisit}

_Generated by HealthPlus AI_`;

    return `https://wa.me/${CLINIC_CONFIG.phone}?text=${encodeURIComponent(message)}`;
  };

  const renderStep = () => {
    switch (currentStep) {
      case Step.Welcome: return <WelcomeStep onStart={() => setCurrentStep(Step.PatientInfo)} />;
      case Step.PatientInfo: return <PatientInfoStep data={formData} update={updateFormData} />;
      case Step.DoctorSelection: return <DoctorSelectionStep data={formData} update={updateFormData} />;
      case Step.DateTimeSelection: return <DateTimeStep data={formData} update={updateFormData} />;
      case Step.Review: return <ReviewStep data={formData} selectedDoctor={selectedDoctor} aiSummary={aiSummary} />;
      case Step.Confirmation: return <ConfirmationStep data={formData} selectedDoctor={selectedDoctor} whatsappUrl={generateWhatsAppURL()} />;
    }
  };

  return (
    <div className="min-h-screen flex flex-col items-center py-10 px-4 relative">
      {/* Background Blobs for Glass Effect */}
      <div className="fixed top-[-10%] left-[-10%] w-[40%] h-[40%] bg-blue-300/30 rounded-full blur-[100px] pointer-events-none" />
      <div className="fixed bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-purple-300/30 rounded-full blur-[100px] pointer-events-none" />

      {/* Glass Header */}
      <header className="w-full max-w-2xl flex items-center justify-between mb-10 px-8 py-5 glass rounded-[2.5rem] shadow-xl shadow-blue-500/5">
        <div className="flex items-center gap-3">
          <div className="bg-gradient-to-tr from-blue-600 to-indigo-500 p-2 rounded-2xl text-white shadow-lg shadow-blue-500/20">
            <ShieldCheck size={24} />
          </div>
          <h1 className="text-2xl font-extrabold text-slate-800 tracking-tight">HealthPlus</h1>
        </div>
        {currentStep > Step.Welcome && currentStep < Step.Confirmation && (
          <div className="px-4 py-1.5 bg-white/40 rounded-full text-xs font-bold text-blue-700 uppercase tracking-wider">
            Step {currentStep} / 4
          </div>
        )}
      </header>

      {/* Progress Indicator */}
      {currentStep > Step.Welcome && currentStep < Step.Confirmation && (
        <div className="w-full max-w-2xl h-2 bg-white/30 rounded-full mb-8 overflow-hidden glass p-0.5">
          <div 
            className="h-full bg-gradient-to-r from-blue-500 to-indigo-400 rounded-full transition-all duration-700 ease-out shadow-[0_0_15px_rgba(59,130,246,0.5)]"
            style={{ width: `${(currentStep / 4) * 100}%` }}
          />
        </div>
      )}

      {/* Main Glass Panel */}
      <main className="w-full max-w-2xl glass rounded-[3rem] shadow-2xl shadow-blue-500/10 p-8 md:p-12 relative overflow-hidden transition-all duration-500">
        <div className="relative z-10">
            {renderStep()}
        </div>
        
        {/* Navigation Buttons */}
        {currentStep > Step.Welcome && currentStep < Step.Confirmation && (
          <div className="mt-12 flex gap-4">
            <button
              onClick={handleBack}
              className="flex-1 py-4 px-6 rounded-3xl bg-white/20 text-slate-600 font-bold text-sm flex items-center justify-center gap-2 hover:bg-white/40 transition-all border border-white/40"
            >
              <ChevronLeft size={18} /> Back
            </button>
            <button
              disabled={!isStepValid || isSummarizing}
              onClick={handleNext}
              className={`flex-[2] py-4 px-6 rounded-3xl font-bold text-sm flex items-center justify-center gap-2 transition-all shadow-xl shadow-blue-500/10
                ${isStepValid && !isSummarizing ? 'bg-gradient-to-r from-blue-600 to-indigo-500 text-white hover:opacity-90 active:scale-[0.98]' : 'bg-slate-300 text-slate-500 cursor-not-allowed shadow-none opacity-50'}`}
            >
              {isSummarizing ? (
                <div className="flex items-center gap-2">
                   <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                   Analyzing Case...
                </div>
              ) : (
                <>
                  {currentStep === Step.Review ? 'Book Appointment' : 'Continue'}
                  <ChevronRight size={18} />
                </>
              )}
            </button>
          </div>
        )}
      </main>

      <p className="mt-10 text-slate-400 text-sm font-semibold flex items-center gap-2">
        <Sparkles size={16} className="text-blue-400" />
        Intelligent Medical Concierge System
      </p>
    </div>
  );
};

// --- Step Components ---

const WelcomeStep: React.FC<{ onStart: () => void }> = ({ onStart }) => (
  <div className="text-center">
    <div className="mb-10 relative">
      <div className="absolute inset-0 bg-blue-500/20 blur-3xl rounded-full" />
      <img 
        src="https://picsum.photos/seed/glass/1000/500" 
        alt="Health Center" 
        className="w-full h-64 object-cover rounded-[2.5rem] relative z-10 shadow-2xl"
      />
    </div>
    <h2 className="text-4xl font-extrabold text-slate-800 mb-4 tracking-tight leading-tight">
        Modern Care for <span className="bg-gradient-to-r from-blue-600 to-indigo-500 bg-clip-text text-transparent">Modern Living.</span>
    </h2>
    <p className="text-slate-500 font-medium mb-10 max-w-sm mx-auto leading-relaxed">
      Connect with world-class specialists in a few clicks. Your journey to wellness begins here.
    </p>
    <button 
      onClick={onStart}
      className="w-full py-5 bg-gradient-to-r from-blue-600 to-indigo-500 text-white rounded-[2rem] font-bold text-xl shadow-2xl shadow-blue-500/20 hover:opacity-90 transition-all active:scale-[0.98]"
    >
      Start Booking
    </button>
    <div className="mt-12 flex justify-center gap-8">
      <div className="text-center">
        <p className="text-slate-800 font-bold text-xl">5.0</p>
        <p className="text-slate-400 text-[10px] font-bold uppercase tracking-widest">Average Rating</p>
      </div>
      <div className="w-px h-10 bg-slate-200" />
      <div className="text-center">
        <p className="text-slate-800 font-bold text-xl">10k+</p>
        <p className="text-slate-400 text-[10px] font-bold uppercase tracking-widest">Successful Visits</p>
      </div>
    </div>
  </div>
);

const PatientInfoStep: React.FC<{ data: FormData, update: (u: Partial<FormData>) => void }> = ({ data, update }) => (
  <div className="space-y-8">
    <div className="flex items-center gap-4">
      <div className="w-12 h-12 glass rounded-2xl flex items-center justify-center text-blue-600">
        <User size={24} />
      </div>
      <div>
        <h2 className="text-2xl font-extrabold text-slate-800 tracking-tight leading-none">Your Identity</h2>
        <p className="text-slate-400 text-xs font-bold mt-1 uppercase tracking-wider">Patient Information</p>
      </div>
    </div>
    <div className="space-y-6">
      <div className="relative">
        <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-2 ml-2">Full Name</label>
        <input 
          type="text" 
          placeholder="Jane Doe"
          className="w-full px-6 py-4 rounded-3xl bg-white/40 border border-white/50 text-slate-800 font-semibold outline-none focus:bg-white/80 transition-all placeholder:text-slate-300"
          value={data.patientName}
          onChange={e => update({ patientName: e.target.value })}
        />
      </div>
      <div className="relative">
        <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-2 ml-2">WhatsApp Contact</label>
        <input 
          type="tel" 
          placeholder="+1 (555) 000-0000"
          className="w-full px-6 py-4 rounded-3xl bg-white/40 border border-white/50 text-slate-800 font-semibold outline-none focus:bg-white/80 transition-all placeholder:text-slate-300"
          value={data.phoneNumber}
          onChange={e => update({ phoneNumber: e.target.value })}
        />
      </div>
      <div className="relative">
        <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-2 ml-2">Health Description</label>
        <textarea 
          placeholder="Briefly describe your symptoms or reason for the visit..."
          rows={4}
          className="w-full p-6 rounded-[2rem] bg-white/40 border border-white/50 text-slate-800 font-semibold outline-none focus:bg-white/80 transition-all placeholder:text-slate-300 resize-none"
          value={data.reasonForVisit}
          onChange={e => update({ reasonForVisit: e.target.value })}
        />
        <div className="mt-2 flex items-center gap-2 text-[10px] text-blue-400 font-bold uppercase tracking-widest ml-2">
           <AlertCircle size={12} /> AI summary will be generated next
        </div>
      </div>
    </div>
  </div>
);

const DoctorSelectionStep: React.FC<{ data: FormData, update: (u: Partial<FormData>) => void }> = ({ data, update }) => (
  <div className="space-y-8">
    <div className="flex items-center gap-4">
      <div className="w-12 h-12 glass rounded-2xl flex items-center justify-center text-indigo-600">
        <Briefcase size={24} />
      </div>
      <div>
        <h2 className="text-2xl font-extrabold text-slate-800 tracking-tight leading-none">Specialist</h2>
        <p className="text-slate-400 text-xs font-bold mt-1 uppercase tracking-wider">Expert Selection</p>
      </div>
    </div>
    <div className="grid gap-4 max-h-[380px] overflow-y-auto pr-2 custom-scrollbar">
      {DOCTORS.map(doc => (
        <button
          key={doc.id}
          onClick={() => update({ doctorId: doc.id })}
          className={`flex items-center p-5 rounded-[2.5rem] transition-all text-left relative group
            ${data.doctorId === doc.id ? 'glass bg-blue-500/10 border-blue-400/50' : 'glass-card'}`}
        >
          <img src={doc.image} alt={doc.name} className="w-20 h-20 rounded-3xl object-cover mr-6 shadow-lg border border-white/50" />
          <div className="flex-1">
            <h3 className="text-lg font-extrabold text-slate-800">{doc.name}</h3>
            <p className="text-sm font-bold text-blue-600/80 mb-2">{doc.specialty}</p>
            <div className="flex gap-4">
               <div className="flex items-center gap-1.5 text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                 <Clock size={12} /> {doc.experience}
               </div>
               <div className="flex items-center gap-1.5 text-[10px] font-bold text-amber-500 uppercase tracking-widest">
                 <Star size={12} fill="currentColor" /> {doc.rating}
               </div>
            </div>
          </div>
          {data.doctorId === doc.id && (
            <div className="absolute right-6 top-1/2 -translate-y-1/2 w-10 h-10 bg-blue-500 rounded-full flex items-center justify-center text-white shadow-xl shadow-blue-500/40">
              <CheckCircle2 size={24} />
            </div>
          )}
        </button>
      ))}
    </div>
  </div>
);

const DateTimeStep: React.FC<{ data: FormData, update: (u: Partial<FormData>) => void }> = ({ data, update }) => (
  <div className="space-y-8">
    <div className="flex items-center gap-4">
      <div className="w-12 h-12 glass rounded-2xl flex items-center justify-center text-blue-500">
        <Calendar size={24} />
      </div>
      <div>
        <h2 className="text-2xl font-extrabold text-slate-800 tracking-tight leading-none">Schedule</h2>
        <p className="text-slate-400 text-xs font-bold mt-1 uppercase tracking-wider">Time Allocation</p>
      </div>
    </div>
    <div className="space-y-8">
      <div>
        <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3 ml-2">Select Date</label>
        <div className="relative">
          <input 
            type="date" 
            className="w-full px-6 py-5 rounded-3xl bg-white/40 border border-white/50 text-slate-800 font-bold outline-none focus:bg-white/80 transition-all"
            value={data.appointmentDate || ''}
            onChange={e => update({ appointmentDate: e.target.value })}
          />
        </div>
      </div>
      <div>
        <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3 ml-2">Available Slots</label>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          {CLINIC_CONFIG.availableHours.map(time => (
            <button
              key={time}
              onClick={() => update({ appointmentTime: time })}
              className={`py-4 rounded-2xl font-bold text-sm transition-all border
                ${data.appointmentTime === time 
                  ? 'bg-blue-600 text-white border-blue-400 shadow-xl shadow-blue-500/20' 
                  : 'bg-white/30 text-slate-600 border-white/40 hover:bg-white/60'}`}
            >
              {time}
            </button>
          ))}
        </div>
      </div>
    </div>
  </div>
);

const ReviewStep: React.FC<{ data: FormData, selectedDoctor?: Doctor, aiSummary: string }> = ({ data, selectedDoctor, aiSummary }) => (
  <div className="space-y-8">
    <div className="flex items-center gap-4">
      <div className="w-12 h-12 glass rounded-2xl flex items-center justify-center text-emerald-500">
        <CheckCircle2 size={24} />
      </div>
      <div>
        <h2 className="text-2xl font-extrabold text-slate-800 tracking-tight leading-none">Confirm</h2>
        <p className="text-slate-400 text-xs font-bold mt-1 uppercase tracking-wider">Final Verification</p>
      </div>
    </div>
    
    <div className="space-y-6">
      <div className="flex items-center gap-6 p-6 rounded-[2rem] glass bg-white/20">
        <img src={selectedDoctor?.image} alt="" className="w-20 h-20 rounded-3xl object-cover border-2 border-white/50 shadow-xl" />
        <div>
          <h4 className="text-xl font-extrabold text-slate-800">{selectedDoctor?.name}</h4>
          <p className="text-sm font-bold text-blue-600/80">{selectedDoctor?.specialty}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="p-5 rounded-[1.5rem] glass bg-white/10">
          <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">Schedule</p>
          <p className="text-sm font-bold text-slate-700">{data.appointmentDate}</p>
          <p className="text-sm font-bold text-blue-600">{data.appointmentTime}</p>
        </div>
        <div className="p-5 rounded-[1.5rem] glass bg-white/10">
          <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">Patient</p>
          <p className="text-sm font-bold text-slate-700 truncate">{data.patientName}</p>
          <p className="text-xs font-bold text-slate-500 mt-0.5">{data.phoneNumber}</p>
        </div>
      </div>

      <div className="p-6 rounded-[2rem] glass-dark text-white relative overflow-hidden">
        <div className="absolute top-0 right-0 p-3 opacity-20">
          <Sparkles size={40} />
        </div>
        <p className="text-[10px] font-bold text-blue-300 uppercase tracking-widest mb-3 flex items-center gap-2">
          <div className="w-2 h-2 bg-blue-400 rounded-full animate-pulse" />
          Intelligent Intake Summary
        </p>
        <p className="text-sm font-medium leading-relaxed italic text-slate-200">
          "{aiSummary || data.reasonForVisit}"
        </p>
      </div>
    </div>
  </div>
);

const ConfirmationStep: React.FC<{ data: FormData, selectedDoctor?: Doctor, whatsappUrl: string }> = ({ data, selectedDoctor, whatsappUrl }) => {
  return (
    <div className="text-center py-6">
      <div className="w-24 h-24 bg-gradient-to-tr from-emerald-400 to-teal-500 text-white rounded-[2.5rem] flex items-center justify-center mx-auto mb-8 shadow-2xl shadow-emerald-400/30">
        <CheckCircle2 size={48} strokeWidth={2.5} />
      </div>
      <h2 className="text-4xl font-extrabold text-slate-800 mb-4 tracking-tight">Summary Verified</h2>
      <p className="text-slate-500 font-medium mb-10 max-w-sm mx-auto leading-relaxed">
        Your booking profile is ready. Finalize your appointment through our encrypted WhatsApp concierge.
      </p>
      
      <button 
        onClick={() => window.open(whatsappUrl, '_blank')}
        className="w-full py-5 bg-gradient-to-r from-emerald-500 to-teal-600 text-white rounded-[2rem] font-bold text-xl shadow-2xl shadow-emerald-500/20 hover:opacity-90 transition-all flex items-center justify-center gap-4 active:scale-[0.98]"
      >
        <MessageCircle size={28} />
        Open WhatsApp Concierge
      </button>
      
      <div className="mt-12 p-5 glass rounded-3xl text-slate-500 text-[10px] font-bold uppercase tracking-widest flex items-center justify-center gap-3">
        <div className="w-2 h-2 bg-emerald-400 rounded-full" />
        Secure Encrypted Link Active
      </div>
    </div>
  );
};

export default App;
