
import React, { useState, useCallback, useMemo } from 'react';
import { 
  ChevronRight, 
  ChevronLeft, 
  Calendar, 
  User, 
  Clock, 
  Phone, 
  CheckCircle2, 
  MessageCircle,
  AlertCircle,
  ShieldCheck,
  Star,
  Users,
  Briefcase,
  Sparkles,
  ClipboardList,
  Stethoscope,
  SendHorizontal,
  Loader2
} from 'lucide-react';
import { Step, FormData, Doctor } from './types';
import { DOCTORS, CLINIC_CONFIG, APPOINTMENT_TYPES } from './constants';
import { summarizeHealthReason } from './services/geminiService';

const WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbwiXvDA_iUUkZQHj5s-EQl6bl07HGuczXILbtph7BTM_vZKQbMBtYwSjSFaOCBX6Ljr7Q/exec";

const App: React.FC = () => {
  const [currentStep, setCurrentStep] = useState<Step>(Step.Welcome);
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [aiSummary, setAiSummary] = useState<string>('');
  const [formData, setFormData] = useState<FormData>({
    patientName: '',
    phoneNumber: '',
    email: '',
    reasonForVisit: '',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '',
    doctorId: null,
    appointmentType: 'consultation'
  });

  const selectedDoctor = useMemo(() => 
    DOCTORS.find(d => d.id === formData.doctorId), 
  [formData.doctorId]);

  const handleNext = async () => {
    if (currentStep === Step.PatientInfo && !aiSummary) {
      setIsSummarizing(true);
      const summary = await summarizeHealthReason(formData.reasonForVisit);
      setAiSummary(summary);
      setIsSummarizing(false);
    }
    setCurrentStep(prev => (prev + 1) as Step);
  };

  const handleBack = () => setCurrentStep(prev => (prev - 1) as Step);

  const updateFormData = (updates: Partial<FormData>) => {
    setFormData(prev => ({ ...prev, ...updates }));
  };

  const isStepValid = useMemo(() => {
    switch (currentStep) {
      case Step.PatientInfo:
        return formData.patientName.length >= 2 && 
               formData.phoneNumber.length >= 8 && 
               formData.reasonForVisit.length >= 10;
      case Step.DoctorSelection:
        return formData.doctorId !== null;
      case Step.DateTimeSelection:
        return !!formData.appointmentDate && !!formData.appointmentTime;
      default:
        return true;
    }
  }, [currentStep, formData]);

  const generateWhatsAppURL = () => {
    const message = `*HealthPlus Concierge Booking*
    
*Patient:* ${formData.patientName}
*Phone:* ${formData.phoneNumber}
*Doctor:* ${selectedDoctor?.name}
*Specialty:* ${selectedDoctor?.specialty}
*Time:* ${formData.appointmentDate} at ${formData.appointmentTime}

*Patient Intake Summary:*
${aiSummary || formData.reasonForVisit}

_Generated by HealthPlus AI_`;

    return `https://wa.me/${CLINIC_CONFIG.phone}?text=${encodeURIComponent(message)}`;
  };

  const handleFinalSubmit = async () => {
    setIsSaving(true);
    try {
      const payload = {
        timestamp: new Date().toLocaleString(),
        patientName: formData.patientName,
        phoneNumber: formData.phoneNumber,
        doctorName: selectedDoctor?.name || 'N/A',
        specialty: selectedDoctor?.specialty || 'N/A',
        date: formData.appointmentDate,
        time: formData.appointmentTime,
        originalReason: formData.reasonForVisit,
        aiSummary: aiSummary,
        status: 'Pending WhatsApp Confirmation'
      };

      await fetch(WEBHOOK_URL, {
        method: 'POST',
        mode: 'no-cors',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload)
      });
      
      setTimeout(() => {
        setIsSaving(false);
        window.open(generateWhatsAppURL(), '_blank');
      }, 800);
      
    } catch (error) {
      console.error("Failed to save to sheet:", error);
      setIsSaving(false);
      window.open(generateWhatsAppURL(), '_blank');
    }
  };

  const renderStep = () => {
    switch (currentStep) {
      case Step.Welcome: return <WelcomeStep onStart={() => setCurrentStep(Step.PatientInfo)} />;
      case Step.PatientInfo: return <PatientInfoStep data={formData} update={updateFormData} />;
      case Step.DoctorSelection: return <DoctorSelectionStep data={formData} update={updateFormData} />;
      case Step.DateTimeSelection: return <DateTimeStep data={formData} update={updateFormData} />;
      case Step.Review: return (
        <ReviewAndSendStep 
          data={formData} 
          selectedDoctor={selectedDoctor} 
          aiSummary={aiSummary} 
          isSaving={isSaving}
          onSend={handleFinalSubmit} 
        />
      );
    }
  };

  const stepsMetadata = [
    { id: Step.PatientInfo, label: 'Profile', icon: User },
    { id: Step.DoctorSelection, label: 'Expert', icon: Stethoscope },
    { id: Step.DateTimeSelection, label: 'Schedule', icon: Calendar },
    { id: Step.Review, label: 'Send', icon: SendHorizontal },
  ];

  return (
    <div className="min-h-screen flex flex-col items-center py-10 px-4 relative">
      <div className="fixed top-[-10%] left-[-10%] w-[40%] h-[40%] bg-blue-300/30 rounded-full blur-[100px] pointer-events-none" />
      <div className="fixed bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-purple-300/30 rounded-full blur-[100px] pointer-events-none" />

      <header className="w-full max-w-2xl flex items-center justify-between mb-8 px-8 py-5 glass rounded-[2.5rem] shadow-xl shadow-blue-500/5">
        <div className="flex items-center gap-3">
          <div className="bg-gradient-to-tr from-blue-600 to-indigo-500 p-2 rounded-2xl text-white shadow-lg shadow-blue-500/20">
            <ShieldCheck size={24} />
          </div>
          <h1 className="text-2xl font-extrabold text-slate-800 tracking-tight">HealthPlus</h1>
        </div>
        <div className="flex items-center gap-2">
            <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse" />
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">AI Concierge Live</span>
        </div>
      </header>

      {currentStep > Step.Welcome && (
        <div className="w-full max-w-2xl px-6 mb-10">
          <div className="flex items-center justify-between relative">
            <div className="absolute top-1/2 left-0 w-full h-0.5 bg-white/30 -translate-y-1/2 z-0 rounded-full" />
            <div 
              className="absolute top-1/2 left-0 h-1 bg-gradient-to-r from-blue-500 to-indigo-400 -translate-y-1/2 z-0 rounded-full transition-all duration-700 ease-in-out shadow-[0_0_10px_rgba(59,130,246,0.3)]"
              style={{ width: `${((currentStep - 1) / (stepsMetadata.length - 1)) * 100}%` }}
            />

            {stepsMetadata.map((step) => {
              const Icon = step.icon;
              const isActive = currentStep === step.id;
              const isCompleted = currentStep > step.id;
              
              return (
                <div key={step.id} className="relative z-10 flex flex-col items-center">
                  <div 
                    className={`w-12 h-12 rounded-2xl flex items-center justify-center transition-all duration-500 border-2 
                      ${isActive 
                        ? 'glass bg-blue-600 text-white border-blue-400 scale-110 shadow-lg shadow-blue-500/30' 
                        : isCompleted 
                          ? 'glass bg-emerald-500 text-white border-emerald-300' 
                          : 'glass bg-white/40 text-slate-400 border-white/40'
                      }`}
                  >
                    {isCompleted ? <CheckCircle2 size={20} /> : <Icon size={20} />}
                  </div>
                  <span 
                    className={`absolute -bottom-7 text-[10px] font-black uppercase tracking-tighter whitespace-nowrap transition-colors duration-500 
                      ${isActive ? 'text-blue-600' : isCompleted ? 'text-emerald-600' : 'text-slate-400'}`}
                  >
                    {step.label}
                  </span>
                </div>
              );
            })}
          </div>
        </div>
      )}

      <main className="w-full max-w-2xl glass rounded-[3rem] shadow-2xl shadow-blue-500/10 p-8 md:p-12 relative overflow-hidden transition-all duration-500 mt-2">
        <div className="relative z-10">
            {renderStep()}
        </div>
        
        {currentStep > Step.Welcome && currentStep < Step.Review && (
          <div className="mt-12 flex gap-4">
            <button
              onClick={handleBack}
              className="flex-1 py-4 px-6 rounded-3xl bg-white/20 text-slate-600 font-bold text-sm flex items-center justify-center gap-2 hover:bg-white/40 transition-all border border-white/40"
            >
              <ChevronLeft size={18} /> Back
            </button>
            <button
              disabled={!isStepValid || isSummarizing}
              onClick={handleNext}
              className={`flex-[2] py-4 px-6 rounded-3xl font-bold text-sm flex items-center justify-center gap-2 transition-all shadow-xl shadow-blue-500/10
                ${isStepValid && !isSummarizing ? 'bg-gradient-to-r from-blue-600 to-indigo-500 text-white hover:opacity-90 active:scale-[0.98]' : 'bg-slate-300 text-slate-500 cursor-not-allowed shadow-none opacity-50'}`}
            >
              {isSummarizing ? (
                <div className="flex items-center gap-2">
                   <Loader2 size={16} className="animate-spin text-white/50" />
                   Analyzing Case...
                </div>
              ) : (
                <>
                  {currentStep === Step.DateTimeSelection ? 'Review Final Packet' : 'Continue'}
                  <ChevronRight size={18} />
                </>
              )}
            </button>
          </div>
        )}
      </main>

      <p className="mt-10 text-slate-400 text-sm font-semibold flex items-center gap-2">
        <Sparkles size={16} className="text-blue-400" />
        Advanced Intelligent Medical Concierge
      </p>
    </div>
  );
};

const WelcomeStep: React.FC<{ onStart: () => void }> = ({ onStart }) => (
  <div className="text-center">
    <div className="mb-10 relative">
      <div className="absolute inset-0 bg-blue-500/20 blur-3xl rounded-full" />
      <img 
        src="https://picsum.photos/seed/glass/1000/500" 
        alt="Health Center" 
        className="w-full h-64 object-cover rounded-[2.5rem] relative z-10 shadow-2xl"
      />
    </div>
    <h2 className="text-4xl font-extrabold text-slate-800 mb-4 tracking-tight leading-tight">
        Modern Care for <span className="bg-gradient-to-r from-blue-600 to-indigo-500 bg-clip-text text-transparent">Modern Living.</span>
    </h2>
    <p className="text-slate-500 font-medium mb-10 max-w-sm mx-auto leading-relaxed text-sm">
      Experience frictionless medical booking powered by intelligent analysis. Your health, simplified.
    </p>
    <button 
      onClick={onStart}
      className="w-full py-5 bg-gradient-to-r from-blue-600 to-indigo-500 text-white rounded-[2rem] font-bold text-xl shadow-2xl shadow-blue-500/20 hover:opacity-90 transition-all active:scale-[0.98]"
    >
      Start Booking
    </button>
    <div className="mt-12 flex justify-center gap-8">
      <div className="text-center">
        <p className="text-slate-800 font-bold text-xl leading-none">5.0</p>
        <p className="text-slate-400 text-[9px] font-bold uppercase tracking-widest mt-1">Average Rating</p>
      </div>
      <div className="w-px h-10 bg-slate-200" />
      <div className="text-center">
        <p className="text-slate-800 font-bold text-xl leading-none">10k+</p>
        <p className="text-slate-400 text-[9px] font-bold uppercase tracking-widest mt-1">Successful Visits</p>
      </div>
    </div>
  </div>
);

const PatientInfoStep: React.FC<{ data: FormData, update: (u: Partial<FormData>) => void }> = ({ data, update }) => (
  <div className="space-y-8">
    <div className="flex items-center gap-4">
      <div className="w-12 h-12 glass rounded-2xl flex items-center justify-center text-blue-600">
        <User size={24} />
      </div>
      <div>
        <h2 className="text-2xl font-extrabold text-slate-800 tracking-tight leading-none">Identity</h2>
        <p className="text-slate-400 text-xs font-bold mt-1 uppercase tracking-wider">Step 01: Profile Setup</p>
      </div>
    </div>
    <div className="space-y-6">
      <div className="relative">
        <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-2 ml-2">Full Name</label>
        <input 
          type="text" 
          placeholder="Jane Doe"
          className="w-full px-6 py-4 rounded-3xl bg-white/40 border border-white/50 text-slate-800 font-semibold outline-none focus:bg-white/80 transition-all placeholder:text-slate-300"
          value={data.patientName}
          onChange={e => update({ patientName: e.target.value })}
        />
      </div>
      <div className="relative">
        <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-2 ml-2">WhatsApp Contact</label>
        <input 
          type="tel" 
          placeholder="+60..."
          className="w-full px-6 py-4 rounded-3xl bg-white/40 border border-white/50 text-slate-800 font-semibold outline-none focus:bg-white/80 transition-all placeholder:text-slate-300"
          value={data.phoneNumber}
          onChange={e => update({ phoneNumber: e.target.value })}
        />
      </div>
      <div className="relative">
        <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-2 ml-2">Reason for Visit</label>
        <textarea 
          placeholder="Briefly describe your symptoms or concern..."
          rows={4}
          className="w-full p-6 rounded-[2rem] bg-white/40 border border-white/50 text-slate-800 font-semibold outline-none focus:bg-white/80 transition-all placeholder:text-slate-300 resize-none"
          value={data.reasonForVisit}
          onChange={e => update({ reasonForVisit: e.target.value })}
        />
        <div className="mt-2 flex items-center gap-2 text-[10px] text-blue-400 font-bold uppercase tracking-widest ml-2">
           <AlertCircle size={12} /> Minimum 10 characters required for AI analysis
        </div>
      </div>
    </div>
  </div>
);

const DoctorSelectionStep: React.FC<{ data: FormData, update: (u: Partial<FormData>) => void }> = ({ data, update }) => (
  <div className="space-y-8">
    <div className="flex items-center gap-4">
      <div className="w-12 h-12 glass rounded-2xl flex items-center justify-center text-indigo-600">
        <Briefcase size={24} />
      </div>
      <div>
        <h2 className="text-2xl font-extrabold text-slate-800 tracking-tight leading-none">Specialist</h2>
        <p className="text-slate-400 text-xs font-bold mt-1 uppercase tracking-wider">Step 02: Expert Matching</p>
      </div>
    </div>
    <div className="grid gap-4 max-h-[380px] overflow-y-auto pr-2 custom-scrollbar">
      {DOCTORS.map(doc => (
        <button
          key={doc.id}
          onClick={() => update({ doctorId: doc.id })}
          className={`flex items-center p-5 rounded-[2.5rem] transition-all text-left relative group
            ${data.doctorId === doc.id ? 'glass bg-blue-500/10 border-blue-400/50' : 'glass bg-white/40 border border-white/50 hover:bg-white/60 shadow-lg'}`}
        >
          <img src={doc.image} alt={doc.name} className="w-20 h-20 rounded-3xl object-cover mr-6 shadow-lg border border-white/50" />
          <div className="flex-1">
            <h3 className="text-lg font-extrabold text-slate-800">{doc.name}</h3>
            <p className="text-sm font-bold text-blue-600/80 mb-2">{doc.specialty}</p>
            <div className="flex gap-4">
               <div className="flex items-center gap-1.5 text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                 <Clock size={12} /> {doc.experience}
               </div>
               <div className="flex items-center gap-1.5 text-[10px] font-bold text-amber-500 uppercase tracking-widest">
                 <Star size={12} fill="currentColor" /> {doc.rating}
               </div>
            </div>
          </div>
          {data.doctorId === doc.id && (
            <div className="absolute right-6 top-1/2 -translate-y-1/2 w-10 h-10 bg-blue-500 rounded-full flex items-center justify-center text-white shadow-xl shadow-blue-500/40">
              <CheckCircle2 size={24} />
            </div>
          )}
        </button>
      ))}
    </div>
  </div>
);

const DateTimeStep: React.FC<{ data: FormData, update: (u: Partial<FormData>) => void }> = ({ data, update }) => (
  <div className="space-y-8">
    <div className="flex items-center gap-4">
      <div className="w-12 h-12 glass rounded-2xl flex items-center justify-center text-blue-500">
        <Calendar size={24} />
      </div>
      <div>
        <h2 className="text-2xl font-extrabold text-slate-800 tracking-tight leading-none">Schedule</h2>
        <p className="text-slate-400 text-xs font-bold mt-1 uppercase tracking-wider">Step 03: Time Selection</p>
      </div>
    </div>
    <div className="space-y-8">
      <div>
        <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3 ml-2">Select Date</label>
        <div className="relative">
          <input 
            type="date" 
            className="w-full px-6 py-5 rounded-3xl bg-white/40 border border-white/50 text-slate-800 font-bold outline-none focus:bg-white/80 transition-all"
            value={data.appointmentDate || ''}
            onChange={e => update({ appointmentDate: e.target.value })}
          />
        </div>
      </div>
      <div>
        <label className="block text-xs font-bold text-slate-400 uppercase tracking-widest mb-3 ml-2">Available Slots</label>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          {CLINIC_CONFIG.availableHours.map(time => (
            <button
              key={time}
              onClick={() => update({ appointmentTime: time })}
              className={`py-4 rounded-2xl font-bold text-sm transition-all border
                ${data.appointmentTime === time 
                  ? 'bg-blue-600 text-white border-blue-400 shadow-xl shadow-blue-500/20' 
                  : 'bg-white/30 text-slate-600 border-white/40 hover:bg-white/60'}`}
            >
              {time}
            </button>
          ))}
        </div>
      </div>
    </div>
  </div>
);

const ReviewAndSendStep: React.FC<{ 
  data: FormData, 
  selectedDoctor?: Doctor, 
  aiSummary: string, 
  isSaving: boolean,
  onSend: () => void 
}> = ({ data, selectedDoctor, aiSummary, isSaving, onSend }) => (
  <div className="space-y-6">
    <div className="text-center mb-8">
      <div className="w-16 h-16 bg-gradient-to-tr from-emerald-400 to-teal-500 text-white rounded-[1.5rem] flex items-center justify-center mx-auto mb-4 shadow-xl shadow-emerald-400/20">
        <CheckCircle2 size={32} strokeWidth={2.5} />
      </div>
      <h2 className="text-3xl font-extrabold text-slate-800 tracking-tight">Final Packet Ready</h2>
      <p className="text-slate-500 text-xs font-bold uppercase tracking-widest mt-1">Verified Medical Intake</p>
    </div>
    
    <div className="space-y-4">
      <div className="flex items-center gap-6 p-5 rounded-[1.5rem] glass bg-white/20">
        <img src={selectedDoctor?.image} alt="" className="w-14 h-14 rounded-2xl object-cover border-2 border-white/50 shadow-lg" />
        <div>
          <h4 className="text-lg font-extrabold text-slate-800 leading-none">{selectedDoctor?.name}</h4>
          <p className="text-xs font-bold text-blue-600/80 mt-1">{selectedDoctor?.specialty}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-3">
        <div className="p-4 rounded-[1.25rem] glass bg-white/10">
          <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Appointment</p>
          <p className="text-xs font-bold text-slate-700">{data.appointmentDate}</p>
          <p className="text-xs font-bold text-blue-600">{data.appointmentTime}</p>
        </div>
        <div className="p-4 rounded-[1.25rem] glass bg-white/10">
          <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Patient</p>
          <p className="text-xs font-bold text-slate-700 truncate">{data.patientName}</p>
          <p className="text-[10px] font-bold text-slate-500">{data.phoneNumber}</p>
        </div>
      </div>

      <div className="p-5 rounded-[1.5rem] glass-dark text-white relative overflow-hidden">
        <div className="absolute top-0 right-0 p-3 opacity-10">
          <Sparkles size={32} />
        </div>
        <p className="text-[9px] font-bold text-blue-300 uppercase tracking-widest mb-2 flex items-center gap-2">
          <div className="w-1.5 h-1.5 bg-blue-400 rounded-full animate-pulse" />
          Intelligent Clinical Brief
        </p>
        <p className="text-xs font-medium leading-relaxed italic text-slate-200">
          "{aiSummary || data.reasonForVisit}"
        </p>
      </div>
    </div>

    <div className="pt-4">
      <button 
        onClick={onSend}
        disabled={isSaving}
        className={`w-full py-5 rounded-[2rem] font-bold text-lg shadow-2xl transition-all flex items-center justify-center gap-3 active:scale-[0.98]
          ${isSaving 
            ? 'bg-slate-400 text-slate-100 cursor-not-allowed shadow-none' 
            : 'bg-gradient-to-r from-emerald-500 to-teal-600 text-white shadow-emerald-500/20 hover:opacity-95'}`}
      >
        {isSaving ? (
          <>
            <Loader2 size={24} className="animate-spin" />
            Syncing Records...
          </>
        ) : (
          <>
            <MessageCircle size={24} />
            Confirm via WhatsApp
          </>
        )}
      </button>
      
      <p className="text-center mt-4 text-[9px] font-bold text-slate-400 uppercase tracking-[0.2em]">
        Instant Verification Enabled
      </p>
    </div>
  </div>
);

export default App;
